# Generated by Django 6.0.6 on 2026-06-26 15:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('school', models.CharField(choices=[('AB', 'AB School'), ('BB', 'BB School'), ('CB', 'CB School')], max_length=2)),
            ],
        ),
    ]
